import { ChevronDown, ChevronUp, Heading, Pilcrow } from 'lucide-react'

import { useT } from '@/i18n/useT'
import { moveBlock, outlineOf } from '@/lib/drafting/outline'
import type { BodyDoc } from '@/lib/drafting/model'
import { cn } from '@/lib/utils'

/**
 * The document's spine, down the left of the editor.
 *
 * Headings and numbered paragraphs, indented by level, each a button that
 * takes the caret there, each with a pair of controls that move it.
 *
 * ### Reordering is buttons FIRST and drag second
 *
 * A move-up/move-down pair is reachable from a keyboard, announced by a screen
 * reader, and works on a phone; native drag-and-drop is none of the three. So
 * the buttons are the implementation and `draggable` is a convenience laid over
 * the same `onMove` call — which is also why there is no drop indicator to get
 * out of sync with anything: the two paths cannot disagree because there is
 * only one of them.
 *
 * ### A move steps over what is UNDER the entry above, not over one block
 *
 * The indices in an outline entry are positions in `body.content`, so a heading
 * with three paragraphs under it is followed in the array by those paragraphs.
 * Moving the next heading "up" one place would bury it inside them. It moves to
 * the index of the entry above instead, which is what an officer means.
 *
 * ### No paragraph numbers
 *
 * Markers are generated by position (ADR-041 §7), so a number printed here
 * would be wrong the instant anything above it moves — on the one screen whose
 * whole purpose is moving things. The level is shown by indentation and stated
 * in the accessible name.
 */
export function DocumentOutline({
  body,
  onChange,
  onJump,
  className,
}: {
  body: BodyDoc
  onChange: (next: BodyDoc) => void
  /** Put the caret at this `body.content` index. */
  onJump: (index: number) => void
  className?: string
}) {
  const { t } = useT()
  const entries = outlineOf(body)

  const move = (position: number, direction: -1 | 1) => {
    const from = entries[position]
    const to = entries[position + direction]
    if (!from || !to) return
    onChange(moveBlock(body, from.index, to.index))
  }

  if (entries.length === 0) {
    return (
      <nav aria-label={t('draft.outline.title')} className={cn('text-sm', className)}>
        <h2 className="mb-2 text-xs font-semibold text-muted-foreground uppercase">
          {t('draft.outline.title')}
        </h2>
        <p className="text-xs text-muted-foreground">{t('draft.outline.empty')}</p>
      </nav>
    )
  }

  return (
    <nav aria-label={t('draft.outline.title')} className={cn('text-sm', className)}>
      <h2 className="mb-2 text-xs font-semibold text-muted-foreground uppercase">
        {t('draft.outline.title')}
      </h2>
      <ol className="flex flex-col">
        {entries.map((entry, position) => {
          const name = entry.text || t('draft.outline.untitled')
          return (
            <li
              key={`${entry.index}-${entry.kind}`}
              draggable
              onDragStart={(event) => event.dataTransfer.setData('text/plain', String(position))}
              onDragOver={(event) => event.preventDefault()}
              onDrop={(event) => {
                event.preventDefault()
                const from = Number(event.dataTransfer.getData('text/plain'))
                const source = entries[from]
                if (!source || from === position) return
                onChange(moveBlock(body, source.index, entry.index))
              }}
              className="group flex items-center gap-0.5"
              style={{ paddingInlineStart: `${(entry.level - 1) * 12}px` }}
            >
              <button
                type="button"
                onClick={() => onJump(entry.index)}
                className="flex min-h-9 min-w-0 flex-1 items-center gap-1.5 rounded-md px-2 text-start text-xs transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:ring-2 focus-visible:ring-ring focus-visible:outline-none"
              >
                {entry.kind === 'heading' ? (
                  <Heading aria-hidden="true" className="h-3.5 w-3.5 shrink-0 text-muted-foreground" />
                ) : (
                  <Pilcrow aria-hidden="true" className="h-3.5 w-3.5 shrink-0 text-muted-foreground" />
                )}
                <span className="min-w-0 flex-1 truncate">{name}</span>
              </button>
              <button
                type="button"
                disabled={position === 0}
                aria-label={t('draft.outline.moveUp', { name })}
                onClick={() => move(position, -1)}
                className="flex h-8 w-6 shrink-0 items-center justify-center rounded-md text-muted-foreground transition-colors hover:bg-accent hover:text-accent-foreground disabled:opacity-30"
              >
                <ChevronUp aria-hidden="true" className="h-3.5 w-3.5" />
              </button>
              <button
                type="button"
                disabled={position === entries.length - 1}
                aria-label={t('draft.outline.moveDown', { name })}
                onClick={() => move(position, 1)}
                className="flex h-8 w-6 shrink-0 items-center justify-center rounded-md text-muted-foreground transition-colors hover:bg-accent hover:text-accent-foreground disabled:opacity-30"
              >
                <ChevronDown aria-hidden="true" className="h-3.5 w-3.5" />
              </button>
            </li>
          )
        })}
      </ol>
    </nav>
  )
}
