import { fileURLToPath, URL } from 'node:url'

import react from '@vitejs/plugin-react'
import { VitePWA } from 'vite-plugin-pwa'
import { defineConfig } from 'vitest/config'

/**
 * Kept as a literal rather than imported from src/i18n/en.json + hi.json: the
 * manifest is generated by Node, outside the app bundle, and a static string
 * avoids JSON-import config across the vite.config.ts / tsconfig.node.json
 * boundary for one field. Must track app.shortDescription in both files.
 */
const MANIFEST_DESCRIPTION_EN =
  'Offline-first reference and productivity tool for central government officers.'
const MANIFEST_DESCRIPTION_HI =
  'केंद्रीय सरकारी अधिकारियों के लिए ऑफ़लाइन-प्रथम संदर्भ एवं कार्य-सहायक उपकरण।'

export default defineConfig({
  plugins: [
    react(),
    VitePWA({
      // Manual registration (src/app/pwa.tsx) drives the update prompt, so
      // the plugin must not also inject its own register script.
      injectRegister: false,
      registerType: 'prompt',
      manifest: {
        name: 'Sahayak · सरकारी सहायक',
        short_name: 'Sahayak',
        description: `${MANIFEST_DESCRIPTION_EN} · ${MANIFEST_DESCRIPTION_HI}`,
        theme_color: '#F7F1E3',
        background_color: '#F7F1E3',
        display: 'standalone',
        start_url: '/',
        lang: 'hi',
        dir: 'ltr',
        categories: ['productivity', 'reference'],
        icons: [
          { src: '/icons/pwa-192x192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
          { src: '/icons/pwa-512x512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
          {
            src: '/icons/maskable-icon-192x192.png',
            sizes: '192x192',
            type: 'image/png',
            purpose: 'maskable',
          },
          {
            src: '/icons/maskable-icon-512x512.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'maskable',
          },
        ],
      },
      workbox: {
        // Everything Vite builds, plus the self-hosted fonts and icons that
        // live in public/ and are copied into the same output directory.
        globPatterns: ['**/*.{js,css,html,woff2,png,svg,ico,webmanifest}'],
        cleanupOutdatedCaches: true,
        clientsClaim: true,
        // Client-routed pages (e.g. /pay) aren't individually precached;
        // serve the cached shell for any navigation the cache can't match.
        navigateFallback: '/index.html',
        runtimeCaching: [
          {
            urlPattern: ({ url }) => url.pathname.startsWith('/data/') && url.pathname.endsWith('.json'),
            handler: 'StaleWhileRevalidate',
            options: {
              cacheName: 'data-v1',
              expiration: { maxAgeSeconds: 30 * 24 * 60 * 60 },
            },
          },
          {
            urlPattern: ({ request }) => request.mode !== 'navigate',
            handler: 'NetworkFirst',
            options: { cacheName: 'runtime-v1' },
          },
        ],
      },
    }),
  ],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url)),
    },
  },
  build: {
    // Keep asset URLs relative-free and predictable for the
    // "no external URL" acceptance test.
    assetsInlineLimit: 0,
  },
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: ['./src/test/setup.ts'],
    css: false,
    include: ['src/**/*.test.{ts,tsx}', 'tests/**/*.test.{ts,tsx}'],
    exclude: ['tests/e2e/**'],
  },
})
