import { z } from 'zod'

import { runAgent, type UsageLedger } from '../agent'
import { buildContext, type BuiltContext, type Snippet } from '../context'
import { buildSystem } from '../prompts'
import type { AiProvider } from '../provider'
import { toJsonSchema, type RegisteredTool } from '../tools/registry'
import {
  EMPTY_USAGE,
  type AiErrorCode,
  type AiEventHandler,
  type AiOutputMeta,
  type AiTier,
  type Bilingual,
  type TokenUsage,
} from '../types'
import { estimateCost } from '../usage'
import { screenOutbound, type BriefRefusal } from './drafting'

import type { Language } from '@/i18n'
import { evaluateChecklist } from '@/lib/drafting/checklist'
import { buildInstruction } from '@/lib/drafting/instructions'
import { bindings, bodySchema, readDoc, type BodyDoc, type OfficialDoc } from '@/lib/drafting/model'
import { proposeChanges, restrictToBlocks, textOf, type DocProposal } from '@/lib/drafting/proposal'
import { renderOfficialDoc } from '@/lib/drafting/renderDoc'
import type { Lang } from '@/lib/drafting/types'
import type { RetrievedSnippet } from '@/lib/retrieval'
import type { DocTemplate } from '@/modules/drafting/schema'

/**
 * Modify by instruction — "make para 3 firmer", "shorten to one page",
 * "translate to Hindi and keep the citations in English".
 *
 * ### It returns a PROPOSAL, never a document
 *
 * The model is handed the officer's document and returns a whole new body. This
 * file never gives that body to anybody. It diffs it against what the officer
 * has (`src/lib/drafting/proposal.ts`), enforces the scope in code, evaluates
 * the checklist over the result, and returns a list of decisions. Nothing is
 * applied until the officer accepts a change, and an accepted set creates a
 * version — so the state before the change is recoverable even after they say
 * yes.
 *
 * That is a stronger guarantee than the drafting agent's, and it is the right
 * one for the difference between the two features: `runDraftingAgent` completes
 * a form the officer is still filling in, while this one CHANGES writing they
 * have already finished.
 *
 * ### Scope is the app's decision, not the model's
 *
 * A scoped instruction ("rewrite this paragraph") tells the model which block,
 * and then {@link runModifyAgent} discards every change outside it and reports
 * what it discarded. The prompt asks for the same thing, and the prompt is not
 * the enforcement — a persona instruction is not a check (ADR-036's lesson,
 * applied to a different failure). The test that matters is the one where a
 * mock returns a document with an out-of-scope block changed and the run comes
 * back with that change gone and a sentence saying so.
 *
 * ### The checklist is evaluated here, over the result
 *
 * The same rule as ADR-032 §1: whatever the agent says about its own output is
 * re-derived in code. A rewrite that reads better and fails `paraNumbering` is
 * a rewrite the officer needs told about BEFORE they accept it, and the model
 * reporting its own checklist is reporting an intention.
 *
 * ### The rationale may not name a paragraph number
 *
 * The prompt says so, and there are two independent reasons — the second is the
 * one worth knowing, because the first would look like a workaround on its own.
 *
 * The real reason is that a paragraph number in this app is GENERATED BY
 * POSITION (`renderDoc.ts`, and the defect `versions.ts#linesOf` was written to
 * fix). A proposal is a set of accept/reject controls, so accepting an
 * insertion renumbers everything below it — and a rationale that said
 * "paragraph 3 has been made firmer" is then talking about a paragraph the
 * officer never touched. Opening words are stable; a position is not.
 *
 * The second reason is that it would fail the run anyway.
 * `context.ts#NUMBERED_PROVISION_PATTERN` matches `para(graph)?\s*N` as a claim
 * about a provision, so "paragraph 3" in an answer that cites no snippet
 * containing a 3 is rejected as an invented citation — the same wall
 * `docs/DATA-GAPS.md` #60 records for the drafting agent, hit from a new
 * direction. `modify.test.ts` asserts the failure rather than leaving it to be
 * discovered, because the failure is loud and the cause is not obvious.
 */

const AGENT_ID = 'doc-modify' as const

/*
  The quick actions and the phase list live in `./modify-actions`, and are
  re-exported here so an existing import of this module keeps working.

  They moved because `ModifyPanel` needs them as VALUES, and a static import of
  this file from the panel defeats `useModifyAi`'s dynamic import of it — which
  is the property that keeps the agent, the renderer, the checklist evaluator
  and zod off the device of a reader who never turns AI on. That file has the
  full note.
*/
import type { ModifyPhase, ModifyStep } from './modify-actions'

export {
  MODIFY_PHASES,
  QUICK_ACTIONS,
  type ModifyPhase,
  type ModifyStep,
  type QuickAction,
} from './modify-actions'

/* ------------------------------------------------------------------ *
 * The shape the model must answer in
 * ------------------------------------------------------------------ */

const bilingual = z.object({ en: z.string(), hi: z.string() })

/**
 * The BODY back, and a rationale.
 *
 * Only the body, and deliberately not the whole `OfficialDoc`: a model handed a
 * document with an `id`, a `createdAt` and a `docModelVersion` will
 * occasionally return them changed, and every one of those is a field this app
 * owns. `proposeChanges` compares meta and vars separately, from the fields the
 * model is allowed to propose below.
 */
const modifySchema = z.object({
  body: z.unknown(),
  rationale: bilingual,
  /** Optional, and each one becomes a decision the officer takes separately. */
  meta: z
    .object({
      subject: z.string().optional(),
      number: z.string().optional(),
      date: z.string().optional(),
      urgency: z.enum(['none', 'immediate', 'priority', 'topPriority']).optional(),
      enclosures: z.array(z.string()).optional(),
    })
    .optional(),
})

/* ------------------------------------------------------------------ *
 * Results
 * ------------------------------------------------------------------ */

export interface ChecklistDelta {
  /** Ids that pass now and did not before. */
  fixed: string[]
  /** Ids that passed before and do not now — the officer must see these. */
  broken: string[]
  mustFailingBefore: number
  mustFailingAfter: number
}

export interface ModifyProposal {
  status: 'proposal'
  proposal: DocProposal
  /** The document as the model returned it, for a whole-document preview. */
  proposed: OfficialDoc
  rationale: Bilingual
  /** Snippet ids the rationale cited, re-derived, never claimed. */
  citations: { id: string; citation: string; href: string }[]
  checklist: ChecklistDelta
  problems: string[]
  usage: TokenUsage
  cost: number
  meta: AiOutputMeta
}

export interface ModifyRefused {
  status: 'refused'
  refusal: BriefRefusal
}

export interface ModifyFailed {
  status: 'error'
  code: AiErrorCode
  message: string
  usage: TokenUsage
  cost: number
}

export type ModifyAgentResult = ModifyProposal | ModifyRefused | ModifyFailed

export interface ModifyAgentParams {
  provider: AiProvider
  doc: OfficialDoc
  template: DocTemplate
  /** What the officer typed, or a `QUICK_ACTIONS` value. */
  instruction: string
  /** Which issue is being changed. */
  lang: Lang
  language: Language
  /**
   * Block indices the change is confined to. Empty means the whole document.
   * Enforced here; the prompt only states it.
   */
  scope?: ReadonlySet<number>
  /** Snippets for any provision the instruction named. The only citable ones. */
  snippets?: readonly RetrievedSnippet[]
  devanagariDigits?: boolean
  tools?: readonly RegisteredTool[]
  signal?: AbortSignal
  onProgress?: (step: ModifyStep) => void
  onEvent?: AiEventHandler
  tier?: AiTier
  budgetLimit?: number | null
  model?: string
  ledger?: UsageLedger
  now?: () => Date
}

/* ------------------------------------------------------------------ *
 * Context
 * ------------------------------------------------------------------ */

const bodyFor = (doc: OfficialDoc, lang: Lang): BodyDoc =>
  lang === 'hi' && doc.bodyHi ? doc.bodyHi : doc.body

/** The document as numbered blocks, which is the unit the scope talks about. */
export function numberedBlocks(doc: OfficialDoc, lang: Lang): string[] {
  return (bodyFor(doc, lang).content ?? [])
    .map(textOf)
    .filter((text) => text.length > 0)
    .map((text, index) => `[block ${index}] ${text}`)
}

function modifyContext(params: {
  doc: OfficialDoc
  template: DocTemplate
  instruction: string
  lang: Lang
  language: Language
  scope: ReadonlySet<number>
  snippets: readonly RetrievedSnippet[]
}): BuiltContext {
  const built = buildInstruction(params.template, bindings(params.doc, params.lang), {
    lang: params.lang,
    instruction: params.instruction,
    ...(params.scope.size > 0
      ? {
          scopeNote: `You may change ONLY these blocks: ${[...params.scope].sort((a, b) => a - b).join(', ')}. Every other block must come back byte for byte as it is. The app discards any change outside them.`,
        }
      : {}),
  })

  const snippets: Snippet[] = [
    { type: 'template', id: 'form', source: params.template.name.en, text: built.text },
    {
      type: 'note',
      id: 'document',
      source: 'the officer’s document, as it stands',
      text: numberedBlocks(params.doc, params.lang).join('\n\n'),
    },
    ...params.snippets.map((snippet): Snippet => ({
      type: snippet.kind === 'section' ? 'section' : 'rule',
      id: snippet.id,
      source: snippet.citation,
      text: snippet.text,
    })),
  ]
  return buildContext(snippets, params.language)
}

const userMessage = (instruction: string, scope: ReadonlySet<number>): string =>
  [
    `Change the document in PLATFORM CONTEXT as follows: ${instruction}`,
    '',
    scope.size > 0
      ? `Change ONLY block ${[...scope].sort((a, b) => a - b).join(', ')}. Return every other block exactly as it is.`
      : 'Return the whole document, changed.',
    '',
    'Answer as JSON:',
    '- body: the document body in the editor’s own JSON — {"type":"doc","content":[…]}. Each top-level entry is one paragraph: {"type":"paragraph","content":[{"type":"text","text":"…"}]}. Use "numberedPara" for a numbered paragraph, "heading" with attrs.level for a heading, "bulletList"/"orderedList" with "listItem" children for a list, "blockquote" for a quotation.',
    '- rationale: {en, hi} — one or two sentences saying what you changed and why. Refer to a paragraph by its opening words, never by a number: the app numbers paragraphs by their position, so a number you write is wrong the moment a paragraph above it is accepted or refused. Cite a numbered snippet as [1], [2] where you relied on one.',
    '- meta: optional. Only include a member here if the instruction was about it.',
    '',
    'Do not renumber paragraphs yourself: the app numbers them. Do not invent a file number, a date, an amount or a citation.',
  ].join('\n')

/* ------------------------------------------------------------------ *
 * The run
 * ------------------------------------------------------------------ */

export async function runModifyAgent(params: ModifyAgentParams): Promise<ModifyAgentResult> {
  const {
    provider,
    doc,
    template,
    instruction,
    lang,
    language,
    scope = new Set<number>(),
    snippets = [],
    devanagariDigits = false,
    tools = [],
    signal,
    onProgress,
    onEvent,
    tier = 'byok',
    budgetLimit = null,
    model,
    ledger,
    now = () => new Date(),
  } = params

  const step = (phase: ModifyPhase, tool?: string) => onProgress?.(tool ? { phase, tool } : { phase })

  /* ---- 1. screen ------------------------------------------------- */

  step('screening')
  const refusal = screenOutbound([
    instruction,
    doc.meta.subject.en,
    doc.meta.subject.hi,
    numberedBlocks(doc, lang).join('\n'),
  ])
  if (refusal) return { status: 'refused', refusal }

  /* ---- 2. change ------------------------------------------------- */

  step('reading')
  const context = modifyContext({ doc, template, instruction, lang, language, scope, snippets })

  step('changing')
  const run = await runAgent({
    agentId: AGENT_ID,
    provider,
    tools,
    /*
      Off, for ADR-035 §1's reason: this pass has no tools and everything it
      may use is numbered PLATFORM CONTEXT. What replaces it is stronger than
      a citation rule, because the output is not prose an officer reads and
      believes — it is a set of accept/reject controls over a diff. Nothing
      reaches the document until they press accept, the scope is enforced in
      code below rather than asked for in the prompt, the body is parsed
      against `bodySchema`'s closed node list and read back through `readDoc`,
      and the checklist is evaluated over the result rather than claimed.
    */
    groundedRequired: false,
    system: buildSystem({ agentId: AGENT_ID, language, context }),
    userMessage: userMessage(instruction, scope),
    jsonSchema: { name: 'document_change', schema: toJsonSchema(modifySchema) },
    context,
    language,
    tier,
    budgetLimit,
    ledger,
    now,
    ...(model ? { model } : {}),
    ...(signal ? { signal } : {}),
    onEvent: (event) => {
      if (event.type === 'toolCall') step('changing', event.call.name)
      onEvent?.(event)
    },
  })

  const usage: TokenUsage = run.usage ?? { ...EMPTY_USAGE }
  const cost = estimateCost(run.meta.model, usage)

  if (!run.ok || run.json === undefined) {
    return {
      status: 'error',
      code: run.error?.code ?? 'provider',
      message: run.error?.message ?? 'The change produced no answer.',
      usage,
      cost,
    }
  }

  const parsed = modifySchema.safeParse(run.json)
  if (!parsed.success) {
    return {
      status: 'error',
      code: 'provider',
      message: `The change did not match the expected shape — ${parsed.error.issues
        .map((issue) => `${issue.path.join('.') || '(root)'}: ${issue.message}`)
        .join('; ')}`,
      usage,
      cost,
    }
  }

  /*
    The body goes through `bodySchema` before anything reads it. `BODY_NODES` is
    a closed list, so a model inventing a `footnote` node is refused here rather
    than landing an unrenderable row in `documents` — which is the same refusal
    `readDoc` makes for a stored document written by a later build.
  */
  const bodyResult = bodySchema.safeParse(parsed.data.body)
  if (!bodyResult.success) {
    return {
      status: 'error',
      code: 'provider',
      message:
        'The change came back in a shape this app cannot store — it used a kind of content the document model does not have. Nothing has been applied.',
      usage,
      cost,
    }
  }

  /* ---- 3. propose, in code --------------------------------------- */

  step('checking')
  const problems: string[] = []
  const proposedMeta = { ...doc.meta }
  const metaPatch = parsed.data.meta
  if (metaPatch) {
    if (metaPatch.subject !== undefined) {
      proposedMeta.subject = { ...proposedMeta.subject, [lang]: metaPatch.subject }
    }
    if (metaPatch.number !== undefined) proposedMeta.number = metaPatch.number
    if (metaPatch.date !== undefined) proposedMeta.date = metaPatch.date
    if (metaPatch.urgency !== undefined) proposedMeta.urgency = metaPatch.urgency
    if (metaPatch.enclosures !== undefined) proposedMeta.enclosures = metaPatch.enclosures
  }

  const proposedRaw: OfficialDoc = {
    ...doc,
    meta: proposedMeta,
    ...(lang === 'hi' && doc.bodyHi ? { bodyHi: bodyResult.data } : { body: bodyResult.data }),
  }

  /*
    Read back through `readDoc` rather than used as constructed. It costs one
    parse and it is what makes "the model returned a document this build can
    open" a checked claim instead of an assumption — the constructed object is
    typed, and a typed object built from `unknown` is a claim, not a check.
  */
  const readBack = readDoc(proposedRaw)
  if (!readBack.ok) {
    return {
      status: 'error',
      code: 'provider',
      message: 'The changed document could not be read back, so nothing has been applied.',
      usage,
      cost,
    }
  }
  const proposed = readBack.doc

  let proposal = proposeChanges(doc, proposed, lang)
  if (scope.size > 0) {
    proposal = restrictToBlocks(proposal, scope)
    for (const dropped of proposal.outOfScope) problems.push(dropped.describe)
  }

  if (!proposal.changed) {
    problems.push('The change produced no difference to the document.')
  }

  /* ---- 4. mark it, in code --------------------------------------- */

  const before = evaluateChecklist(template, renderOfficialDoc(doc, template, lang, { devanagariDigits }))
  const after = evaluateChecklist(template, renderOfficialDoc(proposed, template, lang, { devanagariDigits }))
  const passedBefore = new Set(before.filter((item) => item.passed).map((item) => item.id))
  const passedAfter = new Set(after.filter((item) => item.passed).map((item) => item.id))
  const checklist: ChecklistDelta = {
    fixed: after.filter((item) => item.passed && !passedBefore.has(item.id)).map((item) => item.id),
    broken: before.filter((item) => item.passed && !passedAfter.has(item.id)).map((item) => item.id),
    mustFailingBefore: before.filter((item) => item.severity === 'must' && !item.passed).length,
    mustFailingAfter: after.filter((item) => item.severity === 'must' && !item.passed).length,
  }

  /*
    A rewrite that breaks a `must` item is REPORTED and still offered, which is
    the opposite of `runDraftingAgent`'s revision rule (there, a worse draft is
    thrown away). The difference is who is deciding: this proposal is a list of
    accept/reject controls, so the officer can take the two changes they wanted
    and leave the one that broke the numbering — throwing the whole thing away
    would take the good changes with it.
  */
  for (const id of checklist.broken) {
    const item = before.find((entry) => entry.id === id)
    if (item?.severity === 'must') {
      problems.push(`Accepting every change would fail a required check: ${item.label}.`)
    }
  }

  const citations = run.grounding.citedContextIndices
    .map((index) => context.entries[index - 1])
    .filter((entry) => entry !== undefined)
    .map((entry) => {
      const snippet = snippets.find((each) => each.id === entry.id)
      return snippet
        ? { id: snippet.id, citation: snippet.citation, href: snippet.href }
        : { id: entry.id, citation: entry.source ?? entry.id, href: '' }
    })

  step('done')
  return {
    status: 'proposal',
    proposal,
    proposed,
    rationale: parsed.data.rationale,
    citations,
    checklist,
    problems,
    usage,
    cost,
    meta: run.meta,
  }
}
