import { readFileSync } from 'node:fs'
import { join } from 'node:path'

import { describe, expect, it } from 'vitest'

import { finalTurn } from '../fixtures/drafting-scripts'
import { MockProvider } from '../providers/mock'
import { runModifyAgent, type ModifyAgentResult } from './modify'
import { QUICK_ACTIONS } from './modify-actions'

import { newDoc, type BodyDoc, type OfficialDoc } from '@/lib/drafting/model'
import { acceptAll, applyProposal, decidableBlocks, textOf } from '@/lib/drafting/proposal'
import { docTemplateFileSchema, type DocTemplate } from '@/modules/drafting/schema'

/**
 * Modify by instruction, against `MockProvider` and the real committed O.M.
 *
 * The load-bearing test is `discards a change outside the scope`. Everything
 * else here is the ordinary shape of an agent test; that one is the claim this
 * session makes in code rather than in a prompt, and it is written so that it
 * fails against a version that merely ASKS the model to stay in scope.
 */

const TEMPLATE: DocTemplate = docTemplateFileSchema.parse(
  JSON.parse(
    readFileSync(
      join(import.meta.dirname, '..', '..', '..', 'data', 'drafting', 'templates', 'office-memorandum.json'),
      'utf8',
    ),
  ),
).template

const AT = '2026-09-04T10:00:00.000Z'

const para = (text: string) => ({ type: 'paragraph' as const, content: [{ type: 'text' as const, text }] })
const bodyOf = (...texts: string[]): BodyDoc => ({ type: 'doc', content: texts.map(para) })

const THREE = [
  'The undersigned is directed to refer to the subject mentioned above.',
  'The position has been examined in consultation with the Department of Expenditure.',
  'The information called for may kindly be furnished.',
]

const DOC: OfficialDoc = newDoc({
  id: 'doc-1',
  templateId: 'office-memorandum',
  lang: 'en',
  at: AT,
  body: bodyOf(...THREE),
  meta: {
    number: 'A-11011/4/2026-Estt.',
    date: '12.08.2026',
    subject: { en: 'Children Education Allowance — regarding.', hi: '' },
  },
})

/**
 * Note what it does NOT say: a paragraph number.
 *
 * Paragraph numbers are generated by position, so a rationale naming one is
 * talking about whichever paragraph ends up there after the officer's
 * decisions. `validateCitations` independently rejects it — see the test at the
 * end of this file, which asserts that failure rather than leaving the next
 * person to meet it.
 */
const RATIONALE = {
  en: 'The paragraph beginning “The position has been examined” has been made firmer.',
  hi: '“The position has been examined” से आरंभ होने वाले अनुच्छेद को दृढ़ किया गया है।',
}

const answer = (texts: string[], extra: Record<string, unknown> = {}) => ({
  body: bodyOf(...texts),
  rationale: RATIONALE,
  ...extra,
})

const run = (
  json: unknown,
  overrides: Partial<Parameters<typeof runModifyAgent>[0]> = {},
): { provider: MockProvider; result: Promise<ModifyAgentResult> } => {
  const provider = new MockProvider({ id: 'modify', turns: [finalTurn(json)] })
  return {
    provider,
    result: runModifyAgent({
      provider,
      doc: DOC,
      template: TEMPLATE,
      instruction: 'Make paragraph 2 firmer.',
      lang: 'en',
      language: 'en',
      budgetLimit: null,
      ...overrides,
    }),
  }
}

describe('the happy path', () => {
  it('returns a proposal, not a document', async () => {
    const changed = [...THREE]
    changed[1] = 'The position has been examined and no relaxation is under consideration.'
    const { result } = run(answer(changed))
    const outcome = await result
    expect(outcome.status).toBe('proposal')
    if (outcome.status !== 'proposal') return

    expect(decidableBlocks(outcome.proposal)).toHaveLength(1)
    expect(outcome.rationale.hi).toMatch(/अनुच्छेद/)
    // Nothing is applied. The officer's document is untouched until they accept.
    expect((DOC.body.content ?? []).map(textOf)).toEqual(THREE)
  })

  it('applies exactly what was accepted, when it is accepted', async () => {
    const changed = [...THREE]
    changed[1] = 'The position has been examined and no relaxation is under consideration.'
    const { result } = run(answer(changed))
    const outcome = await result
    if (outcome.status !== 'proposal') throw new Error('expected a proposal')

    const applied = applyProposal(DOC, outcome.proposal, acceptAll(outcome.proposal), 'en', AT)
    expect((applied.doc.body.content ?? []).map(textOf)).toEqual(changed)
  })

  it('gives the model the form’s own instruction and the numbered blocks', async () => {
    const { provider, result } = run(answer(THREE))
    await result
    const system = provider.calls[0]?.system.map((block) => block.text).join('\n') ?? ''
    // The per-template instruction builder, and the block numbering the scope
    // rule talks about.
    expect(system).toMatch(/THIRD person/)
    expect(system).toContain('[block 0]')
    expect(system).toContain('[block 2]')
  })
})

describe('scope', () => {
  it('discards a change outside the scope and says so', async () => {
    // The brief's own test: a model that also rewrote a paragraph nobody asked
    // about. It is written to fail against a version that only asks the model
    // to stay in scope, because it hands the model an out-of-scope change and
    // asserts on what comes BACK.
    const changed = [
      'The model tidied this paragraph too.',
      'The position has been examined and no relaxation is under consideration.',
      THREE[2] as string,
    ]
    const { result } = run(answer(changed), { scope: new Set([1]) })
    const outcome = await result
    if (outcome.status !== 'proposal') throw new Error('expected a proposal')

    const changes = decidableBlocks(outcome.proposal)
    expect(changes).toHaveLength(1)
    expect(changes[0]?.kind === 'changed' && changes[0].after).toMatch(/no relaxation/)
    expect(outcome.problems.join(' ')).toMatch(/outside the selection was rewritten/)

    // And accepting everything still leaves paragraph 1 exactly as it was.
    const applied = applyProposal(DOC, outcome.proposal, acceptAll(outcome.proposal), 'en', AT)
    expect((applied.doc.body.content ?? []).map(textOf)[0]).toBe(THREE[0])
  })

  it('discards a meta change made during a scoped instruction', async () => {
    const changed = [...THREE]
    changed[1] = 'Rewritten.'
    const { result } = run(answer(changed, { meta: { subject: 'Something else' } }), {
      scope: new Set([1]),
    })
    const outcome = await result
    if (outcome.status !== 'proposal') throw new Error('expected a proposal')
    expect(outcome.proposal.fields).toEqual([])
    expect(outcome.problems.join(' ')).toMatch(/meta\.subject\.en was changed outside the selection/)
  })

  it('tells the model which blocks it may change', async () => {
    const { provider, result } = run(answer(THREE), { scope: new Set([1]) })
    await result
    const message = JSON.stringify(provider.calls[0]?.messages ?? [])
    expect(message).toMatch(/Change ONLY block 1/)
  })

  it('allows everything when there is no scope', async () => {
    const { result } = run(answer(['Rewritten first.', 'Rewritten second.', THREE[2] as string]))
    const outcome = await result
    if (outcome.status !== 'proposal') throw new Error('expected a proposal')
    expect(decidableBlocks(outcome.proposal)).toHaveLength(2)
    expect(outcome.problems).toEqual([])
  })
})

describe('what the model may not return', () => {
  it('refuses a body using a node type the document model does not have', async () => {
    const outcome = await run({
      body: { type: 'doc', content: [{ type: 'footnote', content: [{ type: 'text', text: 'x' }] }] },
      rationale: RATIONALE,
    }).result
    expect(outcome.status).toBe('error')
    if (outcome.status !== 'error') return
    expect(outcome.message).toMatch(/a kind of content the document model does not have/)
  })

  it('refuses a body that is not a document at all', async () => {
    const outcome = await run({ body: 'just a string', rationale: RATIONALE }).result
    expect(outcome.status).toBe('error')
  })

  it('refuses an answer missing the rationale', async () => {
    const outcome = await run({ body: bodyOf(...THREE) }).result
    expect(outcome.status).toBe('error')
    if (outcome.status !== 'error') return
    expect(outcome.message).toMatch(/did not match the expected shape/)
  })

  it('never lets the model change the document’s identity', async () => {
    // The schema takes only `body`, `rationale` and a narrow `meta`, so an id
    // or a model version the model returned is not even read.
    const outcome = await run(
      answer(THREE, { id: 'somebody-elses-doc', docModelVersion: 99, createdAt: '1999-01-01' }),
    ).result
    if (outcome.status !== 'proposal') throw new Error('expected a proposal')
    expect(outcome.proposed.id).toBe('doc-1')
    expect(outcome.proposed.docModelVersion).toBe(1)
    expect(outcome.proposed.createdAt).toBe(AT)
  })
})

describe('the checklist', () => {
  it('is evaluated over the result rather than claimed by the model', async () => {
    const changed = [...THREE]
    changed[1] = 'The position has been examined and no relaxation is under consideration.'
    const { result } = run(answer(changed))
    const outcome = await result
    if (outcome.status !== 'proposal') throw new Error('expected a proposal')
    expect(outcome.checklist.mustFailingBefore).toBeGreaterThanOrEqual(0)
    expect(outcome.checklist).toHaveProperty('broken')
    expect(outcome.checklist).toHaveProperty('fixed')
  })

  it('warns when accepting everything would fail a required check', async () => {
    // A rewrite that empties the body fails `allRequired` and `paraNumbering`.
    // It is REPORTED and still offered: the proposal is a set of controls, and
    // throwing the whole thing away would take the good changes with it.
    const { result } = run(answer(['']))
    const outcome = await result
    if (outcome.status !== 'proposal') throw new Error('expected a proposal')
    expect(outcome.checklist.mustFailingAfter).toBeGreaterThan(outcome.checklist.mustFailingBefore)
    expect(outcome.problems.join(' ')).toMatch(/would fail a required check/)
  })

  it('says so when the change made no difference at all', async () => {
    const { result } = run(answer(THREE))
    const outcome = await result
    if (outcome.status !== 'proposal') throw new Error('expected a proposal')
    expect(outcome.proposal.changed).toBe(false)
    expect(outcome.problems.join(' ')).toMatch(/no difference/)
  })
})

describe('the refusal screen', () => {
  it('refuses an instruction naming classified material before a provider is called', async () => {
    const { provider, result } = run(answer(THREE), {
      instruction: 'Rewrite this as a top secret note.',
    })
    expect((await result).status).toBe('refused')
    expect(provider.calls).toHaveLength(0)
  })

  it('refuses when the DOCUMENT carries the marking, not only the instruction', async () => {
    // The officer's own document is sent, and it is the likelier of the two to
    // carry a marking — `screenOutbound`'s reason for existing.
    const doc: OfficialDoc = { ...DOC, body: bodyOf('This CONFIDENTIAL note records the position.') }
    const { provider, result } = run(answer(THREE), { doc })
    expect((await result).status).toBe('refused')
    expect(provider.calls).toHaveLength(0)
  })
})

describe('quick actions', () => {
  it('are instructions the officer could have typed', async () => {
    // Not modes: a preset that took its own code path would be a second
    // feature to test and the officer could not see what it was asking for.
    const { provider, result } = run(answer(THREE), { instruction: QUICK_ACTIONS.shorter })
    await result
    expect(JSON.stringify(provider.calls[0]?.messages ?? [])).toContain('Shorten the document')
  })

  it('are English whatever the interface language is', async () => {
    // The same button must ask for the same thing in both languages.
    const { provider, result } = run(answer(THREE), {
      instruction: QUICK_ACTIONS.formal,
      language: 'hi',
    })
    await result
    expect(JSON.stringify(provider.calls[0]?.messages ?? [])).toContain('Raise the register')
  })
})

describe('the Hindi issue', () => {
  it('compares and writes back the Hindi body', async () => {
    const doc: OfficialDoc = { ...DOC, bodyHi: bodyOf('पहला अनुच्छेद।', 'दूसरा अनुच्छेद।') }
    const { result } = run(
      { body: bodyOf('पहला अनुच्छेद।', 'बदला हुआ दूसरा अनुच्छेद।'), rationale: RATIONALE },
      { doc, lang: 'hi' },
    )
    const outcome = await result
    if (outcome.status !== 'proposal') throw new Error('expected a proposal')
    expect(decidableBlocks(outcome.proposal)).toHaveLength(1)

    const applied = applyProposal(doc, outcome.proposal, acceptAll(outcome.proposal), 'hi', AT)
    expect((applied.doc.bodyHi?.content ?? []).map(textOf)).toEqual([
      'पहला अनुच्छेद।',
      'बदला हुआ दूसरा अनुच्छेद।',
    ])
    // And the English body is untouched.
    expect((applied.doc.body.content ?? []).map(textOf)).toEqual(THREE)
  })
})

describe('progress', () => {
  it('reports every phase, in order', async () => {
    const phases: string[] = []
    const { result } = run(answer(THREE), { onProgress: (step) => phases.push(step.phase) })
    await result
    expect(phases).toEqual(['screening', 'reading', 'changing', 'checking', 'done'])
  })
})

describe('a rationale that names a paragraph number', () => {
  it('fails the run, and the failure is worth knowing about', async () => {
    /*
      `context.ts#NUMBERED_PROVISION_PATTERN` reads `paragraph 2` as a claim
      about a provision, and an answer citing no snippet that contains a 2 is
      rejected as an invented citation — `docs/DATA-GAPS.md` #60's wall, hit
      from a new direction.

      The prompt tells the model to use opening words instead, and it tells it
      for the INDEPENDENT reason that a paragraph number is generated by
      position and is wrong the moment a change above it is accepted. This test
      exists so that the failure has a name if a future prompt edit loses that
      sentence.
    */
    const outcome = await run(
      answer(['One.', 'Two.'], {
        rationale: { en: 'Paragraph 2 has been made firmer.', hi: 'अनुच्छेद 2 दृढ़ किया गया।' },
      }),
    ).result
    expect(outcome.status).toBe('error')
    if (outcome.status !== 'error') return
    expect(outcome.code).toBe('invalid_citation')
  })
})
