import type { Card } from '@/modules/trainer/schema'

/**
 * The stored shape of the Rules Trainer's spaced repetition, and the vocabulary
 * the rest of `src/lib/srs` speaks.
 *
 * Everything here is a plain JSON value — string, number, boolean, null. Not a
 * `Date`, and not a ts-fsrs `Card`. Three reasons, in order of how much they
 * cost to get wrong:
 *
 *  1. Export and import (`transfer.ts`) is a `JSON.stringify` away, and a round
 *     trip has to come back **equal**. A `Date` survives IndexedDB's structured
 *     clone and does not survive JSON.
 *  2. ts-fsrs's own `Card` is its algorithm's working state and carries two
 *     fields it has already marked for removal in 6.0.0. Persisting it would
 *     put the library's release schedule inside the reader's device.
 *  3. An ISO-8601 UTC string sorts lexicographically in the same order it sorts
 *     chronologically, so Dexie can index `due` and answer "what is due" with a
 *     range query rather than a table scan.
 *
 * Nothing in this directory imports React, a component, or a dataset. It is
 * given the cards it is to schedule; see `queue.ts`.
 */

/** What a reader can press. FSRS's `Manual` rating is deliberately not offered. */
export type Grade = 'Again' | 'Hard' | 'Good' | 'Easy'

/** Presentation order, and the order the four buttons appear in. */
export const GRADES = ['Again', 'Hard', 'Good', 'Easy'] as const satisfies readonly Grade[]

/** A grade of `Again` is a lapse. Everything else is a pass. */
export const isLapse = (grade: Grade): boolean => grade === 'Again'

/**
 * Where a card is in its life. Lower-cased spellings of FSRS's `State` enum,
 * because the enum's numeric values are an implementation detail of the
 * library and this is written to a reader's device.
 */
export type SrsState = 'new' | 'learning' | 'review' | 'relearning'

/**
 * One card's schedule. The primary key is `qId` — a `Card.id` from
 * `data/rules/cards/<act>.json`.
 *
 * There is no `act` column, deliberately. The act, the rule, the question and
 * the answer all live in the dataset, which is versioned, regenerated by
 * `scripts/authoring/make_cards.py` and shipped with the build; copying any of
 * it here would create a second copy that a dataset refresh cannot correct.
 * Every function that needs to know which act a card belongs to is handed the
 * catalogue.
 */
export interface SrsCardRow {
  /** `Card.id`. */
  qId: string
  /** ISO-8601 UTC. When the card next wants to be seen. */
  due: string
  /** FSRS stability, in days: the interval at which recall would be 90%. */
  stability: number
  /** FSRS difficulty, 1-10. */
  difficulty: number
  /** Days between the last two reviews, as FSRS reckoned them. */
  elapsed: number
  /** Days FSRS scheduled at the last review. 0 while inside a learning step. */
  scheduled: number
  reps: number
  lapses: number
  state: SrsState
  /** ISO-8601 UTC, or null while the card has never been graded. */
  lastReview: string | null
  lastGrade: Grade | null
  /**
   * Which (re)learning step the card is standing on.
   *
   * Not in the shape this session's brief lists, and it is here because leaving
   * it out is a defect rather than a simplification: FSRS's default steps are
   * `1m, 10m`, so a card halfway through them that comes back from storage as
   * step 0 is sent round the first minute again instead of graduating. It is
   * the one field that cannot be re-derived from the others.
   */
  learningSteps: number
}

/**
 * One answered card. Append-only: this table is the evidence behind every
 * number `stats.ts` reports, so a row is never rewritten.
 *
 * `stateBefore`, `elapsed` and `retrievability` are not in the brief's list and
 * are recorded for one reason: **retention cannot be measured from the card
 * rows.** A card row holds where the schedule is now, and grading it overwrites
 * where it was. "Of the cards you had actually learnt, what share did you
 * recall?" is a question about the state a card was in when it was asked, and
 * if that is not written down at the moment of the review, it is gone.
 */
export interface ReviewLogRow {
  /** `<qId>#<reps>#<at>` — see `engine.ts`. Stable across an export/import. */
  id: string
  qId: string
  grade: Grade
  /** ISO-8601 UTC. */
  at: string
  /** Time from the card being shown to the grade being pressed. */
  durationMs: number
  /** The card's state as the reader was shown it. */
  stateBefore: SrsState
  /** Days since the previous review of this card, 0 for a first sight. */
  elapsed: number
  /**
   * What FSRS predicted the chance of recall to be, just before the grade was
   * pressed. Null for a card in `new` state, which has no memory to predict on.
   */
  retrievability: number | null
}

/**
 * One day of work, keyed by its **IST** calendar date (`YYYY-MM-DD`). See
 * `day.ts` for why the boundary is Asia/Kolkata and not the device's zone.
 */
export interface StreakRow {
  date: string
  reviewed: number
  /** The day's queue was emptied. `day.ts#currentStreak` counts these. */
  goalMet: boolean
}

/** The knobs. One row, in a table, so a future knob needs no migration. */
export interface TrainerSettings {
  /** New cards introduced per IST day, across every enabled act. */
  dailyNew: number
  /** Cards already in learning or review shown per IST day. */
  dailyReviewCap: number
  /** FSRS `request_retention`: the recall probability the schedule aims at. */
  desiredRetention: number
  /** Act ids to draw from. **Empty means every act** — see `queue.ts`. */
  actsEnabled: string[]
}

export interface TrainerSettingsRow extends TrainerSettings {
  id: 'trainer'
}

export const TRAINER_SETTINGS_ID = 'trainer'

export const DEFAULT_TRAINER_SETTINGS: TrainerSettings = {
  dailyNew: 10,
  dailyReviewCap: 100,
  desiredRetention: 0.9,
  actsEnabled: [],
}

/**
 * FSRS throws outside `(0, 1]`, and a retention of 0.999 asks for intervals of
 * hours forever. The floor and ceiling are what a slider would offer.
 */
export const MIN_DESIRED_RETENTION = 0.7
export const MAX_DESIRED_RETENTION = 0.98

/** One card the reader is about to be asked, with its schedule beside it. */
export interface QueueItem {
  qId: string
  card: Card
  /** Null only for a card that has never been seen and has no row yet. */
  srs: SrsCardRow | null
  kind: 'review' | 'new'
}
