import type { BodyDoc, BodyNode } from './model'

/**
 * A document's outline, and the one operation that reorders it.
 *
 * ### Why an outline is headings and numbered paragraphs and nothing else
 *
 * An official document's spine is its headings and its numbered paragraphs —
 * "2.", "2.1", "Grounds of appeal". A list item, a table row and a run of
 * ordinary prose are inside one of those, not beside them, and an outline that
 * listed every block would be the document again at half the width.
 *
 * ### No paragraph NUMBERS here, deliberately
 *
 * ADR-041 §7 records that markers are generated by POSITION, so inserting a
 * paragraph renumbers everything below it. An outline that printed "2.1"
 * against an entry would be printing a number that is wrong the moment anything
 * above it moves — and this is the screen whose whole purpose is moving things.
 * It shows the `level` (which is stored on the node) and the text, and the
 * renderer stays the only thing that decides what a paragraph is called.
 *
 * ### `index` is the position in `body.content`, not in the outline
 *
 * That is what makes "jump to this" and "move this" refer to the same thing.
 * A caller moving an entry up computes the target from the PREVIOUS entry's
 * index, so a heading steps over the paragraphs under the one above it rather
 * than swapping with the block immediately before it.
 */

export type OutlineKind = 'heading' | 'numberedPara'

export interface OutlineEntry {
  /** Position in `body.content` — the only index anything else here takes. */
  index: number
  kind: OutlineKind
  /** 1-3 for both kinds. A heading's `level`, a numbered paragraph's depth. */
  level: number
  /** The block's own text, flattened. Empty where the officer has typed none. */
  text: string
}

/** Every run of text under a node, in order, with nothing invented between. */
export function textOfNode(node: BodyNode | undefined): string {
  if (!node) return ''
  if (typeof node.text === 'string') return node.text
  const children = Array.isArray(node.content) ? node.content : []
  return children.map((child) => textOfNode(child)).join('')
}

const levelOf = (node: BodyNode): number => {
  const attrs = (node.attrs ?? {}) as { level?: unknown }
  const level = Number(attrs.level)
  return Number.isFinite(level) ? Math.min(3, Math.max(1, Math.round(level))) : 1
}

export function outlineOf(body: BodyDoc): OutlineEntry[] {
  const blocks = body.content ?? []
  const entries: OutlineEntry[] = []
  blocks.forEach((node, index) => {
    if (node.type !== 'heading' && node.type !== 'numberedPara') return
    entries.push({
      index,
      kind: node.type,
      level: levelOf(node),
      text: textOfNode(node).trim(),
    })
  })
  return entries
}

/**
 * Move one top-level block to another position.
 *
 * Returns the SAME document when there is nothing to do — an out-of-range
 * index, or a move to where the block already is — so a caller can hand the
 * result straight to `setBody` without a change that is not a change creating a
 * version and marking the document dirty.
 */
export function moveBlock(body: BodyDoc, from: number, to: number): BodyDoc {
  const blocks = [...(body.content ?? [])]
  if (from < 0 || from >= blocks.length) return body
  if (to < 0 || to >= blocks.length) return body
  if (from === to) return body
  const [moved] = blocks.splice(from, 1)
  if (!moved) return body
  blocks.splice(to, 0, moved)
  return { ...body, content: blocks }
}
