import { diffWords, type DiffPart } from '@/lib/diff'

import { projectBody, linesOfNodes } from './renderDoc'
import type { BodyDoc, OfficialDoc } from './model'
import type { Lang } from './types'

/**
 * Version snapshots, and the diff between any two of them.
 *
 * Three rules, and the third is the one that makes versions worth having:
 *
 * 1. **A snapshot is taken on every export, on a manual save, and every twenty
 *    edits** — the caller decides which; `shouldAutoSnapshot` is the counter.
 * 2. **Thirty are kept and the oldest is pruned.** A drafting session produces
 *    hundreds of edits, and an unbounded list is one nobody scrolls.
 * 3. **Restoring is not destructive.** `restoreInto` returns a NEW document
 *    body and leaves the version list alone, so the state being restored FROM
 *    is itself snapshotted first by the caller. Nothing in this app deletes an
 *    officer's writing to make room for their own earlier writing.
 *
 * The diff is two-level, deliberately. A document is a list of blocks, and a
 * word-level diff over the whole thing turns an inserted paragraph into a
 * ripple through every paragraph after it. So blocks are matched first — by
 * exact text, then in order — and only a block that CHANGED is diffed word by
 * word, with `src/lib/diff.ts`, which the Law Converter and the drafting
 * suggestion review already use.
 */

export const VERSION_CAP = 30
export const AUTO_SNAPSHOT_EVERY = 20

export type SnapshotReason = 'export' | 'manual' | 'auto' | 'restore'

export interface DocVersion {
  id: string
  docId: string
  at: string
  reason: SnapshotReason
  /** What the officer called it, when they saved it themselves. */
  label: string
  /** The whole document, as it was. */
  doc: OfficialDoc
}

/** True when this edit is the twentieth since the last snapshot. */
export const shouldAutoSnapshot = (editsSinceSnapshot: number): boolean =>
  editsSinceSnapshot > 0 && editsSinceSnapshot % AUTO_SNAPSHOT_EVERY === 0

/**
 * The list, capped, newest first.
 *
 * A manually labelled version is NOT protected from pruning, and that is a
 * decision rather than an oversight: protecting it would make the cap
 * unbounded in the one case where an officer has been diligent, and a
 * thirty-deep list already reaches back through a whole day's work.
 */
export function prune(versions: readonly DocVersion[], cap = VERSION_CAP): DocVersion[] {
  return [...versions].sort((a, b) => compareAt(b.at, a.at)).slice(0, cap)
}

/**
 * Newest first, by CODE UNIT.
 *
 * Not `localeCompare`: ICU collation depends on the locale and on the ICU build
 * the runtime happens to ship, and `prune` does not merely display a list — it
 * slices it, and its caller deletes everything that fell off. Two devices
 * holding the same version list must keep the same thirty.
 * `src/lib/srs/types.ts#compareStrings` states the same rule for the Trainer's
 * export, and `purity.test.ts` here enforces it across this directory.
 *
 * Every `at` is what `toISOString()` produced, which is fixed-width and ASCII,
 * so code-unit order IS chronological order.
 */
export const compareAt = (a: string, b: string): number => (a < b ? -1 : a > b ? 1 : 0)

// -------------------------------------------------------------------- diff

export type BlockChange =
  | { kind: 'unchanged'; index: number; text: string }
  | { kind: 'added'; index: number; text: string }
  | { kind: 'removed'; index: number; text: string }
  /**
   * `words` is `null` when the paragraph is past `src/lib/diff.ts`'s token
   * ceiling — a distinct answer from "no differences", and the caller shows
   * both texts plainly rather than a frozen tab.
   */
  | { kind: 'changed'; index: number; before: string; after: string; words: DiffPart[] | null }

export interface DocDiff {
  blocks: BlockChange[]
  /** Meta fields whose value differs, with both sides. */
  meta: { field: string; before: string; after: string }[]
  changed: boolean
}

const bodyFor = (doc: OfficialDoc, lang: Lang): BodyDoc =>
  lang === 'hi' && doc.bodyHi ? doc.bodyHi : doc.body

/**
 * The paragraphs of a document, WITHOUT their automatic numbers.
 *
 * This is the fix for a defect the test above caught: paragraph markers are
 * generated by position, so inserting a paragraph renumbers every line below
 * it — and a diff run over the numbered text reports one insertion as a change
 * to the whole rest of the document. That ripple is precisely what the
 * block-then-word design exists to avoid, so the block match runs on the words
 * and the marker is presentation.
 *
 * A list item keeps ITS marker, because a bullet or a roman numeral is part of
 * what the officer wrote rather than something the renderer counted.
 */
const linesOf = (doc: OfficialDoc, lang: Lang): string[] =>
  projectBody(bodyFor(doc, lang), lang)
    .map((node) => {
      if (node.kind === 'para') return node.runs.map((run) => run.text).join('')
      return linesOfNodes([node]).join(' ')
    })
    .filter((line) => line.trim().length > 0)

const META_FIELDS = (doc: OfficialDoc, lang: Lang): { field: string; value: string }[] => [
  { field: 'number', value: doc.meta.number },
  { field: 'date', value: doc.meta.date },
  { field: 'subject', value: doc.meta.subject[lang] },
  { field: 'urgency', value: doc.meta.urgency },
  { field: 'status', value: doc.status },
  { field: 'to', value: doc.meta.to.map((person) => person.name[lang] || person.name.en).join('; ') },
  { field: 'copyTo', value: doc.meta.copyTo.map((person) => person.name[lang] || person.name.en).join('; ') },
  { field: 'enclosures', value: doc.meta.enclosures.join('; ') },
]

/**
 * Block-level first, then word-level inside a block that changed.
 *
 * The matching walks both lists once. An identical line at the same position is
 * unchanged; a line whose counterpart is identical LATER in the other list is a
 * removal or an addition; anything else is a change and gets a word diff. That
 * is a simple algorithm rather than a real LCS, and it is the right one here:
 * a document's paragraphs are long and distinctive, so exact-line matching
 * finds the alignment, and where it does not the word diff still says what
 * happened.
 */
export function diffDocuments(before: OfficialDoc, after: OfficialDoc, lang: Lang = 'en'): DocDiff {
  const left = linesOf(before, lang)
  const right = linesOf(after, lang)
  const blocks: BlockChange[] = []

  let i = 0
  let j = 0
  let index = 0
  while (i < left.length || j < right.length) {
    const a = left[i]
    const b = right[j]
    if (a === undefined) {
      blocks.push({ kind: 'added', index: index++, text: b ?? '' })
      j += 1
      continue
    }
    if (b === undefined) {
      blocks.push({ kind: 'removed', index: index++, text: a })
      i += 1
      continue
    }
    if (a === b) {
      blocks.push({ kind: 'unchanged', index: index++, text: a })
      i += 1
      j += 1
      continue
    }
    // Does this left line reappear later on the right? Then everything before
    // it on the right was inserted.
    const laterOnRight = right.indexOf(a, j + 1)
    const laterOnLeft = left.indexOf(b, i + 1)
    if (laterOnRight !== -1 && (laterOnLeft === -1 || laterOnRight - j <= laterOnLeft - i)) {
      blocks.push({ kind: 'added', index: index++, text: b })
      j += 1
      continue
    }
    if (laterOnLeft !== -1) {
      blocks.push({ kind: 'removed', index: index++, text: a })
      i += 1
      continue
    }
    blocks.push({
      kind: 'changed',
      index: index++,
      before: a,
      after: b,
      // `exact: true` for the reason `SuggestionDiff` passes it: what is shown
      // as changed has to be what actually changed, punctuation and capitals
      // included, because an officer comparing two versions is looking for
      // exactly the differences a fuzzy diff folds away (ADR-032).
      words: diffWords(a, b, { exact: true }),
    })
    i += 1
    j += 1
  }

  const beforeMeta = META_FIELDS(before, lang)
  const afterMeta = META_FIELDS(after, lang)
  const meta = beforeMeta
    .map((entry, position) => ({
      field: entry.field,
      before: entry.value,
      after: afterMeta[position]?.value ?? '',
    }))
    .filter((entry) => entry.before !== entry.after)

  return {
    blocks,
    meta,
    changed: meta.length > 0 || blocks.some((block) => block.kind !== 'unchanged'),
  }
}

/**
 * A restored document.
 *
 * The version's content with the LIVE document's identity and timestamps: the
 * same `id`, the same `createdAt`, and `updatedAt` moved to now. Restoring must
 * not fork the document into a second row, and it must not claim the document
 * was created when the version was taken.
 */
export function restoreInto(live: OfficialDoc, version: DocVersion, at: string): OfficialDoc {
  return {
    ...version.doc,
    id: live.id,
    createdAt: live.createdAt,
    updatedAt: at,
    // The restored content is a draft again by definition: a document restored
    // to an earlier state is not the thing that was sent.
    status: live.status === 'sent' ? 'sent' : 'draft',
  }
}

// ---------------------------------------------------------------- comments

export interface DocComment {
  id: string
  docId: string
  /**
   * Which block the comment is anchored to — the index in the body's own
   * `content` array.
   *
   * An index rather than a node id, because Tiptap does not give nodes stable
   * ids and adding one would put a field in the stored document that only
   * comments read. The cost is that a comment anchored to paragraph 4 follows
   * position 4 rather than the sentence, and `blockText` is stored beside it so
   * a comment whose paragraph has moved can still be shown with the words it
   * was about — the same "keep the quote" rule `resolveAnchor` follows for a
   * Library highlight (ADR-039 §1).
   */
  blockIndex: number
  blockText: string
  text: string
  resolved: boolean
  createdAt: string
  updatedAt: string
}

/** A comment whose block still says what it said. */
export const commentIsAnchored = (comment: DocComment, body: BodyDoc, lang: Lang = 'en'): boolean => {
  const lines = linesOfNodes(projectBody(body, lang))
  return lines[comment.blockIndex] === comment.blockText
}
