#!/usr/bin/env python3
"""Fetch the public rule books into ``scripts/authoring/sources/``.

    scripts/ingest/.venv/bin/python scripts/authoring/fetch_sources.py
    scripts/authoring/fetch_sources.py --act ccs-conduct        # just one
    scripts/authoring/fetch_sources.py --report-only            # rewrite SOURCES.md

``sources/`` is git-ignored. These are large published documents that anyone can
download from the Ministry that issued them, and committing 90 MB of them would
put a copy of the rule book in the repository rather than a citation to it. What
IS committed is ``SOURCES.md`` — every URL, the file it produced, its size and
its SHA-256 — so a later disagreement about what was read is settleable, and
``data/rules/text/*.json`` carries the same URL on every record.

This script is on no cron and never will be. A rule book changes when a Ministry
amends it, and an amendment is a reading job (the same reason ``pay_matrix.py``
and ``drafting_seed.py`` are hand-run).
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

import requests

sys.path.insert(0, str(Path(__file__).resolve().parent))

from authoring_common import (  # noqa: E402
    ACTS,
    ACTS_BY_ID,
    AUTHORING_DIR,
    SOURCES_DIR,
    Act,
    Document,
    FetchError,
    Forbidden,
    build_ca_bundle,
    fetch,
    log,
    read_json,
    utc_now,
    write_json,
)

MANIFEST = SOURCES_DIR / "_manifest.json"
SOURCES_MD = AUTHORING_DIR / "SOURCES.md"

PREAMBLE = """<!-- Generated by scripts/authoring/fetch_sources.py. Do not edit by hand. -->

# Sources for the Rules Trainer

Every rule book the trainer is built over, where it is published, and the exact
bytes that were read. The files themselves live in `scripts/authoring/sources/`,
which is **git-ignored** — these are large published documents anyone can
download from the Ministry that issued them, and committing 90 MB of them would
put a copy of the rule book in the repository instead of a citation to it. This
table is the citation, and it is enough to fetch the same bytes again.

Refresh it with:

```bash
scripts/ingest/.venv/bin/python scripts/authoring/fetch_sources.py
```

Three things worth knowing before you add a source.

**Nothing here is on a cron.** A rule book changes when a Ministry amends it,
and an amendment is a reading job — the same reason `pay_matrix.py` and
`drafting_seed.py` are hand-run (ADR-016, ADR-020).

**Several Government of India hosts serve an incomplete TLS chain.**
`documents.doptcirculars.nic.in` omits its Let's Encrypt intermediate, and
`www.istm.gov.in` chains to *ISRG Root YR*, which is newer than the `certifi`
bundle our pinned `requests` ships with. Both are missing-link problems, not
invalid certificates, so `authoring_common.build_ca_bundle()` supplies the
missing links — fetched from `letsencrypt.org` over a connection that verifies
against the roots we already trust, and with ISRG Root YR taken in its
**cross-signed-by-X1** form so no anchor is trusted that does not chain to one
certifi already has. Certificate verification is on for every request in this
directory; `verify=False` appears nowhere and `test_authoring.py` asserts it.

**A 403 is an answer.** As in `scripts/ingest/`, a refusal stops the fetch for
that document — no retry, no mirror, no second user agent.

"""


def fetch_document(act: Act, document: Document, *, ca_bundle: Path, session: requests.Session) -> dict[str, Any]:
    """Fetch one document and write it, returning its manifest entry."""
    target = SOURCES_DIR / document.filename
    entry: dict[str, Any] = {
        "act": act.id,
        "lang": document.lang,
        "title": document.title,
        "kind": document.kind,
        "file": document.filename,
        "urls": list(document.urls),
        "note": document.note,
    }
    try:
        got = fetch(document.urls, ca_bundle=ca_bundle, session=session)
    except Forbidden as error:
        log(f"  ! {document.filename}: {error}")
        return {**entry, "status": "forbidden", "error": str(error)}
    except FetchError as error:
        log(f"  ! {document.filename}: {error}")
        return {**entry, "status": "failed", "error": str(error)}

    SOURCES_DIR.mkdir(parents=True, exist_ok=True)
    target.write_bytes(got.content)
    log(f"  ok {document.filename} ({len(got.content):,} bytes) <- {got.url}")
    return {
        **entry,
        "status": "ok",
        "url": got.url,
        "bytes": len(got.content),
        "sha256": got.sha256,
        "fetchedAt": got.fetched_at,
    }


def render_sources_md(manifest: dict[str, Any]) -> str:
    """The committed citation table, one section per act."""
    by_act: dict[str, list[dict[str, Any]]] = {}
    for entry in manifest["documents"]:
        by_act.setdefault(entry["act"], []).append(entry)

    lines = [PREAMBLE.rstrip(), ""]
    lines.append(f"_Last fetched: {manifest['fetchedAt'][:10]}._")
    lines.append("")

    for act in ACTS:
        entries = by_act.get(act.id, [])
        lines.append(f"## {act.name_en}")
        lines.append("")
        lines.append(f"**{act.name_hi}** · `{act.id}` · {act.unit_en}-numbered · {act.publisher}")
        lines.append("")
        lines.append(f"Landing page: <{act.landing_url}>")
        if act.note:
            lines.append("")
            lines.append(f"> {act.note}")
        lines.append("")
        lines.append("| Lang | Document | File | Bytes | SHA-256 | Status |")
        lines.append("| ---- | -------- | ---- | ----- | ------- | ------ |")
        for entry in entries:
            digest = entry.get("sha256", "")
            short = f"`{digest[:16]}…`" if digest else "—"
            size = f"{entry['bytes']:,}" if entry.get("bytes") else "—"
            lines.append(
                f"| {entry['lang']} | {entry['title']} | `{entry['file']}` | {size} | {short} | "
                f"{entry['status']} |"
            )
        lines.append("")
        for entry in entries:
            url = entry.get("url") or entry["urls"][0]
            lines.append(f"- `{entry['file']}` ← <{url}>")
            if entry.get("note"):
                lines.append(f"  - {entry['note']}")
            if entry.get("error"):
                first = entry["error"].splitlines()[0]
                lines.append(f"  - **not fetched:** {first}")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--act", action="append", help="fetch only this act id (repeatable)")
    parser.add_argument("--report-only", action="store_true", help="rewrite SOURCES.md from the manifest")
    parser.add_argument("--force-ca", action="store_true", help="rebuild the CA bundle")
    args = parser.parse_args()

    if args.report_only:
        manifest = read_json(MANIFEST)
        if manifest is None:
            log("! no manifest; run a fetch first")
            return 1
        SOURCES_MD.write_text(render_sources_md(manifest), encoding="utf-8")
        log(f"wrote {SOURCES_MD.relative_to(AUTHORING_DIR.parent.parent)}")
        return 0

    wanted = set(args.act or [act.id for act in ACTS])
    unknown = wanted - set(ACTS_BY_ID)
    if unknown:
        log(f"! unknown act id(s): {', '.join(sorted(unknown))}")
        return 1

    session = requests.Session()
    ca_bundle = build_ca_bundle(session=session, force=args.force_ca)
    log(f"CA bundle: {ca_bundle}")

    previous = read_json(MANIFEST, default={"documents": []})
    kept = {(e["act"], e["file"]): e for e in previous["documents"] if e["act"] not in wanted}

    entries: list[dict[str, Any]] = []
    for act in ACTS:
        if act.id not in wanted:
            entries.extend(e for (a, _f), e in kept.items() if a == act.id)
            continue
        log(f"{act.id}:")
        for document in act.documents:
            entries.append(fetch_document(act, document, ca_bundle=ca_bundle, session=session))

    order = {(act.id, doc.filename): i for i, (act, doc) in enumerate(
        (a, d) for a in ACTS for d in a.documents
    )}
    entries.sort(key=lambda e: order.get((e["act"], e["file"]), 10**6))

    manifest = {"fetchedAt": utc_now(), "documents": entries}
    write_json(MANIFEST, manifest)
    SOURCES_MD.write_text(render_sources_md(manifest), encoding="utf-8")

    failed = [e for e in entries if e["status"] != "ok"]
    ok = len(entries) - len(failed)
    log(f"{ok}/{len(entries)} documents fetched")
    for entry in failed:
        log(f"  ! {entry['file']}: {entry['status']}")
    log(f"wrote {SOURCES_MD}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
