#!/usr/bin/env node
/**
 * Turn `coverage/coverage-summary.json` into the committed `docs/COVERAGE.md`.
 *
 * The report is committed, and `.github/workflows/ci.yml` fails on a diff, so
 * the numbers in the repository are always the numbers the last green run
 * measured. That is the point of committing it: a coverage figure that lives
 * only in a CI log is a figure nobody reads, and a badge served from a
 * third-party shield would be the one outbound request this app does not make
 * (CLAUDE.md's hard rules, `tests/no-external-urls.test.ts`). So the badge here
 * is text.
 *
 * Run it after `pnpm test:coverage`:
 *
 *     pnpm test:coverage && node scripts/coverage-summary.mjs
 */

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const summaryPath = resolve(root, 'coverage/coverage-summary.json')
const outPath = resolve(root, 'docs/COVERAGE.md')

/** The floor `vite.config.ts` enforces. Kept in step by the test below. */
const THRESHOLD = 90

let summary
try {
  summary = JSON.parse(readFileSync(summaryPath, 'utf8'))
} catch {
  console.error(
    `No coverage data at ${relative(root, summaryPath)}.\n` +
      `Run \`pnpm test:coverage\` first — this script only formats what that produced.`,
  )
  process.exit(1)
}

const pct = (value) => `${value.toFixed(2)}%`

/** A text badge, because a shields.io image would be an outbound request. */
function badge(lines) {
  if (lines >= 95) return '🟢'
  if (lines >= THRESHOLD) return '🟡'
  return '🔴'
}

const files = Object.entries(summary)
  .filter(([key]) => key !== 'total')
  .map(([key, value]) => ({
    file: relative(root, key),
    lines: value.lines,
    branches: value.branches,
    functions: value.functions,
  }))
  // Weakest first: the top of the table is where the next test belongs.
  .sort((a, b) => a.lines.pct - b.lines.pct || a.file.localeCompare(b.file))

const total = summary.total

const rows = files
  .map(
    (entry) =>
      `| \`${entry.file}\` | ${pct(entry.lines.pct)} | ${entry.lines.covered}/${entry.lines.total} | ` +
      `${pct(entry.functions.pct)} | ${pct(entry.branches.pct)} |`,
  )
  .join('\n')

const body = `# Coverage — \`src/lib/**\`

${badge(total.lines.pct)} **${pct(total.lines.pct)} of lines**, ${pct(total.functions.pct)} of functions,
${pct(total.statements.pct)} of statements, ${pct(total.branches.pct)} of branches —
over ${files.length} files and ${total.lines.total} lines.

> Generated by \`scripts/coverage-summary.mjs\` from \`coverage/coverage-summary.json\`.
> **Do not edit by hand**: \`.github/workflows/ci.yml\` regenerates it and fails on a diff, so
> the figures here are always the ones the last green run measured. Refresh with
> \`pnpm test:coverage && node scripts/coverage-summary.mjs\`.

## What is measured, and why only this

\`src/lib\` is the pure layer — every calculation, every schedule, every search ranking, every
rendered document. It is the only part of this app where a number can be wrong without anyone
noticing, which is why it is the part with a threshold: \`vite.config.ts\` fails the run below
${THRESHOLD}% of lines, functions or statements.

Everything else is covered where its own failure mode lives rather than by line count.
Components are covered by \`src/app/App.a11y.test.tsx\` and \`tests/e2e/a11y.spec.ts\` (rendering,
in a real browser, where a contrast or ARIA defect actually exists); the datasets under \`/data\`
by \`tests/*-data.test.ts\` reading the committed bytes off disk; the privacy rule by the
automatic network gate in \`tests/e2e/fixtures.ts\`. See \`docs/TESTING.md\`.

## Per file, weakest first

| File | Lines | Covered | Functions | Branches |
| ---- | ----: | ------: | --------: | -------: |
${rows}

## Notes on what is not covered

Branch coverage is deliberately not thresholded. What remains uncovered is defensive: an
unreachable \`return null\` at the end of a Myers diff that always terminates earlier, a
\`typeof caches === 'undefined'\` arm that only one of the two environments can take, and the
\`never\` arms of exhaustive switches whose whole purpose is to fail a build rather than run.
A threshold that forced those to be exercised would be a threshold that rewarded writing tests
for code that cannot execute.
`

writeFileSync(outPath, body)
console.log(
  `${relative(root, outPath)} — ${pct(total.lines.pct)} of lines across ${files.length} files` +
    (total.lines.pct < THRESHOLD ? `  ⚠️  below the ${THRESHOLD}% threshold` : ''),
)
