#!/usr/bin/env python3
"""Turn `pay_orders.py`'s one-line JSON result into a pull request body.

    scripts/ingest/.venv/bin/python scripts/ingest/pay_orders_pr_body.py <result.json> <out.md>

Kept separate from `pay_orders.py` itself so that script's own stdout
contract (one JSON object, nothing else) stays exactly that — this is
presentation for `.github/workflows/ingest-pay.yml`, not part of the ingest.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path


def render(result: dict) -> str:
    lines: list[str] = []
    da_order = result.get("daOrder")

    if da_order:
        lines.append(
            f"The Dearness Allowance watch found a new order at {da_order['url']} and parsed a rate change:"
        )
        lines.append("")
        lines.append(f"- **{da_order['oldRate']}% → {da_order['newRate']}%**, effective {da_order['effectiveFrom']}")
        lines.append("")
        lines.append("What the order itself says, around the matched sentence:")
        lines.append("")
        lines.append(f"> {da_order['snippet']}")
        if da_order.get("warnings"):
            lines.append("")
            lines.append("**Before merging:**")
            for warning in da_order["warnings"]:
                lines.append(f"- {warning}")
        lines.append("")
        lines.append(f"[Read the order]({da_order['url']}) before merging — this PR only proposes the change.")
        lines.append("")
    else:
        lines.append(
            "The Dearness Allowance watch found nothing new — this pull request only updates "
            "`data/_meta/seen-orders.json`'s bookkeeping so already-reviewed items are not reported again. "
            "No data changed."
        )
        lines.append("")

    manual_review = result.get("manualReview") or []
    if manual_review:
        lines.append(f"This run also opened {len(manual_review)} \"Manual review\" issue(s) for orders it could "
                      "not resolve on its own — see the Issues tab.")
        lines.append("")

    lines.append("Generated by `.github/workflows/ingest-pay.yml`. Never auto-merged.")
    return "\n".join(lines) + "\n"


def main() -> int:
    if len(sys.argv) != 3:
        print("usage: pay_orders_pr_body.py <result.json> <out.md>", file=sys.stderr)
        return 2

    result = json.loads(Path(sys.argv[1]).read_text(encoding="utf-8"))
    Path(sys.argv[2]).write_text(render(result), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
